spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/efa-main
    username: ${EFA_POSTGRES_UNAME}
    password: ${EFA_POSTGRES_PASSWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      # set to validate after setup, set to update if schema changed
      ddl-auto: ${EFA_DDL_AUTO}
efa:
  meta:
    version: RELEASE-NULL